name: 'cmake'
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-cmake:
    strategy:
      matrix:
        cc: ["gcc", "clang"] # "zig cc"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install
        run: |
          sudo apt-get install -y --no-install-recommends build-essential clang libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev
      - name: CMake
        run: |
          CC="${{matrix.cc}}" cmake .
          make -j4
