name: 'uncrustify'
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-uncrustify:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: |
          cd $HOME
          sudo apt-get install -y --no-install-recommends curl cmake build-essential
          curl -L -o uncrustify-0.75.1.tar.gz https://github.com/uncrustify/uncrustify/archive/refs/tags/uncrustify-0.75.1.tar.gz
          tar -xzf uncrustify-0.75.1.tar.gz
          cd uncrustify-uncrustify-0.75.1
          mkdir build
          cd build
          cmake ..
          make -j4
      - name: Uncrustify
        run: |
          cd $GITHUB_WORKSPACE
          FILES=`find editor engine -not \( -path engine/external -prune \) -name \*.\[ch\]`
          $HOME/uncrustify-uncrustify-0.75.1/build/uncrustify \
            -c uncrustify.cfg \
            --no-backup \
            --replace \
            $FILES
          git --no-pager diff --exit-code
